// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdfncaihuzgokfukkazi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkZm5jYWlodXpnb2tmdWtrYXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjA2NjMsImV4cCI6MjA2NzQzNjY2M30.kyk2q5KHKkLIx743QDswtw1Ja0MQXm2uedfMxVi04ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});